[package]
name = "brewtracker-rs"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.19"
crossterm = "0.25"
serde_json = "1.0"
serde = { version = "1.0.164", features = ["derive"]}